services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\PayPalModule\GraphQL\Controller\:
    resource: 'GraphQL/Controller/*'
    public: true
    calls:
      - [setStorefrontBasketService, ['@?OxidEsales\GraphQL\Storefront\Basket\Service\Basket']]

  OxidEsales\PayPalModule\GraphQL\Service\NamespaceMapper:
    class: OxidEsales\PayPalModule\GraphQL\Service\NamespaceMapper
    tags: [ 'graphql_namespace_mapper' ]

  OxidEsales\PayPalModule\GraphQL\Subscriber\BeforePlaceOrder:
    class: OxidEsales\PayPalModule\GraphQL\Subscriber\BeforePlaceOrder
    tags: [ 'kernel.event_subscriber' ]

  OxidEsales\PayPalModule\GraphQL\Service\Basket:
    class: OxidEsales\PayPalModule\GraphQL\Service\Basket
    public: true
    calls:
      - [setSharedBasketInfrastructure, ['@?OxidEsales\GraphQL\Storefront\Shared\Infrastructure\Basket']]
      - [setBasketRelationService, ['@?OxidEsales\GraphQL\Storefront\Basket\Service\BasketRelationService']]

  OxidEsales\PayPalModule\GraphQL\Service\Payment:
    class: OxidEsales\PayPalModule\GraphQL\Service\Payment
    public: true
    calls:
      - [setSharedBasketInfrastructure, ['@?OxidEsales\GraphQL\Storefront\Shared\Infrastructure\Basket']]
      - [setBasketRelationService, ['@?OxidEsales\GraphQL\Storefront\Basket\Service\BasketRelationService']]

  OxidEsales\PayPalModule\GraphQL\Service\BeforePlaceOrder:
    class: OxidEsales\PayPalModule\GraphQL\Service\BeforePlaceOrder
    public: true
    calls:
      - [setStorefrontBasketService, ['@?OxidEsales\GraphQL\Storefront\Basket\Service\Basket']]
      - [setBasketRelationService, ['@?OxidEsales\GraphQL\Storefront\Basket\Service\BasketRelationService']]
